User/dfriend01/102 python hints
UBCSailbot/docs pull request #109
Opened 2022-11-12 03:08 UTC by DFriend01

### Description

- Resolves #102

Added type hinting section in the Python Conventions section.

We should check that type hinting is worth holding as a standard, as the syntax takes some effort to get used to. However, the benefit is that `mypy` allows us to incrementally add type hinting to our code, so our code will not break even if everything does not have type hinting. This would more be for documentation and linting purposes.

2022-11-12 08:58 UTC, patrick-5546 requested changes
Great work overall, left a couple comments.

One more thing, can you create an infra issue in sailbot_workspace to add mypy to its vscode extensions and tasks, CI, and dev image? Thanks

2022-11-12 08:58 UTC, patrick-5546 commented on docs/reference/python/conventions.md
> +### Type hinting and static type checking
I think this section can be brought out of the documentation section, can put it before. Also, can be renamed to just "Type hinting"

2022-11-12 08:58 UTC, patrick-5546 commented on docs/reference/python/conventions.md
> +software architecture. There is some syntax to get familiar in order to use type checking. We recommend the following
Explain why we type hint first
- helps catch errors through static type checking
    - mypy is a static type checker

2022-11-12 08:58 UTC, patrick-5546 commented on docs/reference/python/conventions.md
> +        return sum(seq)
Code examples should pass flake8
- 2 spaces between the imports and constants sections, as well as between any classes or global functions

2022-11-12 09:00 UTC, patrick-5546 commented on docs/reference/python/conventions.md
> +### Type hinting and static type checking
This also brings up the discussion of whether we are doing this just for documentation purposes, or for the added benefit of static type checking

2022-11-28 06:07 UTC, patrick-5546 reviewed
Should we talk about when to use or not to use type hinting?

2022-12-02 02:17 UTC, DFriend01 commented
I added the cons of type hinting and the rules of thumb from the guide you sent: https://realpython.com/lessons/pros-and-cons-type-hints/

I made sure to cite it.

EDIT: I changed my mind. I just added a link to the guide instead because we didn't add anything unique. May as well just link people to the guide itself.

2023-01-13 20:05 UTC, patrick-5546 requested changes

2023-01-13 20:05 UTC, patrick-5546 commented on docs/reference/python/conventions.md
> +### Type hinting
Can create 2 sections under style guide:

```md
## Style guide

### Linting

### Type hinting
```

2023-01-13 20:05 UTC, patrick-5546 commented on docs/reference/python/conventions.md
> +hinting, make sure that you are aware of them before deciding to utilize them in your codebase.
Not sure if this sentence is necessary:

- The link is cited at the bottom of the page
- Target audience is firstly sailbot members, who aren't the ones to decide whether to use type hints

2023-01-13 20:05 UTC, patrick-5546 commented on docs/reference/python/conventions.md
> +??? example "Return the sum of a sequence"
To make it easier to skim read, consider leaving 1 or 2 examples open by default. Can do the same for documentation examples.

2023-01-29 21:49 UTC, patrick-5546 approved these changes

2023-01-29 21:56 UTC, merged