Update setup instructions
UBCSailbot/docs pull request #198
Opened 2024-01-29 04:00 UTC by patrick-5546

### Description
Based on questions asked during the work party yesterday

2024-01-30 08:55 UTC, DFriend01 requested changes

2024-01-30 08:55 UTC, DFriend01 commented on docs/current/sailbot_workspace/setup.md
>      Windows has a native file system as well as file systems for each WSL distribution.
Also might be worth mentioning that sailbot workspace will literally not work if it's cloned on the Windows filesystem. Docker needs to run in WSL.

2024-01-30 19:24 UTC, patrick-5546 commented on docs/current/sailbot_workspace/setup.md
>      Windows has a native file system as well as file systems for each WSL distribution.
Is that not what is says?

2024-01-31 21:28 UTC, DFriend01 approved these changes

2024-01-31 21:28 UTC, DFriend01 commented
@patrick-5546 Check out the change I made to the tip on cloning.

2024-01-31 22:15 UTC, merged