Create ROS reference page
UBCSailbot/docs pull request #50
Opened 2022-09-17 02:04 UTC by patrick-5546

* Resolves #29

2022-09-17 02:13 UTC, patrick-5546 commented
@DFriend01 @hhenry01 

I have made some good progress on our ROS documentation. If you have time, can you try going through the tutorials I listed, and let me know what you think? Much appreciated

#### Notes

- Use the `support_tutorials` branch of sailbot_workspace
- So far I have only verified that tutorials up to and including "Creating a workspace" work

2022-09-28 02:26 UTC, DFriend01 commented on docs/reference/ros.md
> +Installing and setting up ROS without our workspace is outside the scope of this site.
Consider adding a quick blurb saying that installation instructions are on the ROS official documentation if they are interested in running it on bare metal.

2022-09-28 02:29 UTC, DFriend01 commented on docs/reference/ros.md
> +for them altogether.
Any examples of what functionalities are accomplished using the workspace? If there are not too many, a quick exhaustive list would be nice.

2022-09-28 02:33 UTC, DFriend01 requested changes
I only had one comment. Once that is addressed, this PR looks good to me.

2022-09-28 06:15 UTC, hhenry01 approved these changes
Looks good to me.

2022-09-28 07:05 UTC, DFriend01 approved these changes

2022-09-28 07:05 UTC, merged